#!/bin/bash
echo "Running `basename "$0"`"

# fix for a problem with DNS
echo "\
options timeout:0.2
options attempts:40
options single-request" |\
while read a
do
    grep "$a" /etc/resolv.conf || echo "$a" >> /etc/resolv.conf
done
