#!/bin/bash
echo "Running `basename "$0"`"

test -f /mail_settings/dkim/domains && cat /mail_settings/dkim/domains > /etc/amavis/conf.d/51-dkim-domains
test -d /mail_settings/dkim/keys && chown amavis: /mail_settings/dkim/keys/* && chmod 400 /mail_settings/dkim/keys/*
