#!/bin/bash
echo "Running `basename "$0"`"

RANDOM_PASSWORD=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w20 | head -n1)
export PGUSER=postgres
echo "ALTER ROLE $PGUSER WITH PASSWORD '$RANDOM_PASSWORD';" | psql

